# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  branches:
    production:
      - step:
          caches:
            - node
            - docker
          script:
            - npm install
            - npm install --only=dev
            - npm install -g webpack gulp
            - npm run build
            - docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASSWORD
            - docker build -t $DOCKER_HUB_USER/cloudcfo:production .
            - docker push $DOCKER_HUB_USER/cloudcfo:production
          services:
            - docker

