DROP TABLE IF EXISTS `checklist_documents`;
CREATE TABLE `checklist_documents` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT,
    `taskId` BIGINT,
    `documentId` BIGINT,
    `checklistId` BIGINT,
    `isDeleted` TINYINT(1) DEFAULT '0',
    `dateAdded` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `dateUpdated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
) ENGINE=INNODB;