DROP TABLE IF EXISTS `notes`;
CREATE TABLE `notes` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT,
    `projectId` BIGINT,
    `workstreamId` BIGINT,
    `note` VARCHAR(255),
    `privacyType` ENUM("Private","Public"),
    `createdBy` BIGINT,
    `isDeleted` TINYINT DEFAULT '0',
    `dateAdded` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `dateUpdated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
) ENGINE=INNODB;