DROP TABLE IF EXISTS `team`;

CREATE TABLE `team` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT,
    `team` VARCHAR(50),
    `usersId` BIGINT,
    `teamLeaderId` BIGINT,
    `isActive` TINYINT(1) DEFAULT '1',
    `isDeleted` TINYINT(1) DEFAULT '0',
    `dateAdded` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    `dateUpdated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
) ENGINE=INNODB;