DROP TABLE IF EXISTS `terms_and_conditions`;
CREATE TABLE `terms_and_conditions` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT,
    `termsAndConditions` TEXT,
    `dateAdded` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `dateUpdated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
) ENGINE=INNODB;